[language-server.hx-lsp]
command = "target/debug/hx-lsp"
# command = "hx-lsp"
args = ["--log"] # for dev

[[language]]
name = "markdown"
language-servers = ["hx-lsp"]

[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "hx-lsp"
]
