[language-server.hx-lsp]
command = "target/debug/hx-lsp"
args = ["--log"] # for dev

[language-server.hx-lsp.config]
arg1="test1"
path="~/.config/snippets"


[[language]]
name = "markdown"
text-width = 80
soft-wrap = { enable = true, wrap-at-text-width = true }
language-servers = ["hx-lsp"]
