[language-server.hx-lsp]
command = "target/debug/hx-lsp"
args = ["--log"] # for dev

# dev
[language-server.hx-lsp.config]
editor="helix"
path="~/.config/utils-lsp"

[[language]]
name = "markdown"
text-width = 80
soft-wrap = { enable = true, wrap-at-text-width = true }
language-servers = ["hx-lsp"]
